spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/smartcart_user_db
spring.datasource.username=root
spring.datasource.password=devanshu1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true