spring.application.name=config-server
#This is just giving service a name


server.port=8888
#below, it uses git to source the configurations
spring.cloud.config.server.git.uri=https://github.com/d3v0904/SmartCart
spring.cloud.config.server.git.default-label=main